name: horoscope

type: python

up:
  - python: 2.7.13
  - pip:
    - requirements.txt
commands:
  crawler:
    desc: "Run crawler"
    run: python -m crawler.crawler
  data_clean:
    desc: "Run data cleaner"
    run: python -m data_products.data_clean
  nb:
    desc: "Run jupyter notebooks"
    run: jupyter notebook
